__author__ = 'ewino'

# QR error correct levels
ERROR_CORRECT_L = 0
ERROR_CORRECT_M = 1
ERROR_CORRECT_Q = 2
ERROR_CORRECT_H = 3

# QR encoding modes (based on qrcode package)
MODE_NUMBER = 1
MODE_ALPHA_NUM = 2
MODE_BYTES = 4
MODE_KANJI = 8
MODE_ECI = 7
MODE_STRUCTURED_APPEND = 3

# Encoding mode sizes.
MODE_SIZE_SMALL = {
    MODE_NUMBER: 10,
    MODE_ALPHA_NUM: 9,
    MODE_BYTES: 8,
    MODE_KANJI: 8,
}
MODE_SIZE_MEDIUM = {
    MODE_NUMBER: 12,
    MODE_ALPHA_NUM: 11,
    MODE_BYTES: 16,
    MODE_KANJI: 10,
}
MODE_SIZE_LARGE = {
    MODE_NUMBER: 14,
    MODE_ALPHA_NUM: 13,
    MODE_BYTES: 16,
    MODE_KANJI: 12,
}


ALPHANUM_CHARS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:'
